import type { EditorThemeClasses } from 'lexical'

export const editorTheme: EditorThemeClasses = {
  paragraph: 'mb-2 text-slate-100',
  heading: {
    h1: 'text-2xl font-bold mb-2 text-white',
    h2: 'text-xl font-bold mb-2 text-white',
    h3: 'text-lg font-semibold mb-1 text-white',
  },
  quote: 'border-l-4 border-emerald-500/40 pl-4 italic text-slate-300 my-2',
  text: {
    bold: 'font-bold text-white',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    code: 'bg-slate-800/60 text-emerald-300 px-1.5 py-0.5 rounded text-[0.875em] font-mono',
  },
  list: {
    ul: 'list-disc ml-5 mb-2',
    ol: 'list-decimal ml-5 mb-2',
    listitem: 'mb-0.5 text-slate-100',
    nested: {
      listitem: 'list-none',
    },
  },
  link: 'text-emerald-300 underline hover:text-emerald-200 cursor-pointer',
  code: 'block bg-slate-900/80 text-slate-100 font-mono text-sm p-3 rounded-lg my-2 overflow-x-auto whitespace-pre border border-white/10',
  codeHighlight: {
    atrule: 'text-purple-300',
    attr: 'text-yellow-300',
    boolean: 'text-orange-300',
    builtin: 'text-cyan-300',
    cdata: 'text-slate-400',
    char: 'text-green-300',
    class: 'text-cyan-300',
    'class-name': 'text-cyan-300',
    comment: 'text-slate-500 italic',
    constant: 'text-orange-300',
    deleted: 'text-red-400',
    doctype: 'text-slate-400',
    entity: 'text-yellow-300',
    function: 'text-yellow-300',
    important: 'text-red-300',
    inserted: 'text-green-300',
    keyword: 'text-purple-300 font-semibold',
    namespace: 'text-slate-300',
    number: 'text-orange-300',
    operator: 'text-slate-300',
    prolog: 'text-slate-400',
    property: 'text-blue-300',
    punctuation: 'text-slate-400',
    regex: 'text-red-300',
    selector: 'text-green-300',
    string: 'text-green-300',
    symbol: 'text-orange-300',
    tag: 'text-red-300',
    url: 'text-blue-300',
    variable: 'text-red-200',
  },
}
