import type { EditorThemeClasses } from 'lexical'

export const editorTheme: EditorThemeClasses = {
  paragraph: 'mb-2 text-text-primary',
  heading: {
    h1: 'text-2xl font-bold mb-2 text-text-primary',
    h2: 'text-xl font-bold mb-2 text-text-primary',
    h3: 'text-lg font-semibold mb-1 text-text-primary',
  },
  quote: 'border-l-4 border-brand-border pl-4 italic text-text-secondary my-2',
  text: {
    bold: 'font-bold text-text-primary',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    code: 'bg-surface-muted text-brand-primary px-1.5 py-0.5 rounded text-[0.875em] font-mono',
  },
  list: {
    ul: 'list-disc ml-5 mb-2',
    ol: 'list-decimal ml-5 mb-2',
    listitem: 'mb-0.5 text-text-primary',
    nested: {
      listitem: 'list-none',
    },
  },
  link: 'text-brand-primary underline hover:brightness-110 cursor-pointer',
  code: 'block bg-surface-muted text-text-primary font-mono text-sm p-3 rounded-lg my-2 overflow-x-auto whitespace-pre border border-surface-border-soft',
  codeHighlight: {
    atrule: 'text-purple-500',
    attr: 'text-yellow-600',
    boolean: 'text-orange-500',
    builtin: 'text-cyan-600',
    cdata: 'text-text-muted',
    char: 'text-green-600',
    class: 'text-cyan-600',
    'class-name': 'text-cyan-600',
    comment: 'text-text-muted italic',
    constant: 'text-orange-500',
    deleted: 'text-red-500',
    doctype: 'text-text-muted',
    entity: 'text-yellow-600',
    function: 'text-yellow-600',
    important: 'text-red-500',
    inserted: 'text-green-600',
    keyword: 'text-purple-500 font-semibold',
    namespace: 'text-text-secondary',
    number: 'text-orange-500',
    operator: 'text-text-secondary',
    prolog: 'text-text-muted',
    property: 'text-blue-500',
    punctuation: 'text-text-muted',
    regex: 'text-red-500',
    selector: 'text-green-600',
    string: 'text-green-600',
    symbol: 'text-orange-500',
    tag: 'text-red-500',
    url: 'text-blue-500',
    variable: 'text-red-400',
  },
}
