import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { asc, eq, sql } from 'drizzle-orm';
import { randomUUID } from 'node:crypto';
import { DatabaseService } from '../database/database.service';
import { technicalDebtCategoriesTable as technicalDebtPlaybookCategoriesTable, technicalDebtDocumentsTable as technicalDebtPlaybookDocumentsTable, technicalDebtTopicsTable as technicalDebtPlaybookTopicsTable } from '../database/schema';
import type { DocumentInput, DocumentPatchInput, TitleInput } from './technical-debt.schemas';

@Injectable()
export class TechnicalDebtPlaybookService {
  constructor(private readonly databaseService: DatabaseService) {}
  private get db() { return this.databaseService.db; }
  private now() { return new Date().toISOString(); }

  list(userId: string) {
    const categories = this.db.select().from(technicalDebtPlaybookCategoriesTable).where(eq(technicalDebtPlaybookCategoriesTable.userId, userId)).orderBy(asc(technicalDebtPlaybookCategoriesTable.orderIdx), asc(technicalDebtPlaybookCategoriesTable.createdAt)).all();
    const topics = this.db.select().from(technicalDebtPlaybookTopicsTable).orderBy(asc(technicalDebtPlaybookTopicsTable.orderIdx), asc(technicalDebtPlaybookTopicsTable.createdAt)).all();
    const documents = this.db.select().from(technicalDebtPlaybookDocumentsTable).orderBy(asc(technicalDebtPlaybookDocumentsTable.orderIdx), asc(technicalDebtPlaybookDocumentsTable.createdAt)).all();
    return categories.map((category) => ({ ...category, topics: topics.filter((topic) => topic.categoryId === category.id).map((topic) => ({ ...topic, documents: documents.filter((document) => document.topicId === topic.id) })) }));
  }

  createCategory(userId: string, input: TitleInput) { const id = `technicaldebt-cat-${randomUUID().slice(0, 12)}`; const now = this.now(); const max = this.db.select({ max: sql<number>`coalesce(max(${technicalDebtPlaybookCategoriesTable.orderIdx}), -1)` }).from(technicalDebtPlaybookCategoriesTable).where(eq(technicalDebtPlaybookCategoriesTable.userId, userId)).get(); this.db.insert(technicalDebtPlaybookCategoriesTable).values({ id, userId, title: input.title, orderIdx: Number(max?.max ?? -1) + 1, createdAt: now, updatedAt: now }).run(); return this.list(userId).find((item) => item.id === id); }
  updateCategory(userId: string, id: string, input: TitleInput) { this.ensureCategory(userId, id); this.db.update(technicalDebtPlaybookCategoriesTable).set({ title: input.title, updatedAt: this.now() }).where(eq(technicalDebtPlaybookCategoriesTable.id, id)).run(); return this.list(userId).find((item) => item.id === id); }
  deleteCategory(userId: string, id: string) { this.ensureCategory(userId, id); this.db.delete(technicalDebtPlaybookCategoriesTable).where(eq(technicalDebtPlaybookCategoriesTable.id, id)).run(); return { success: true }; }
  createTopic(userId: string, categoryId: string, input: TitleInput) { this.ensureCategory(userId, categoryId); const id = `technicaldebt-topic-${randomUUID().slice(0, 12)}`; const now = this.now(); const max = this.db.select({ max: sql<number>`coalesce(max(${technicalDebtPlaybookTopicsTable.orderIdx}), -1)` }).from(technicalDebtPlaybookTopicsTable).where(eq(technicalDebtPlaybookTopicsTable.categoryId, categoryId)).get(); this.db.insert(technicalDebtPlaybookTopicsTable).values({ id, categoryId, title: input.title, orderIdx: Number(max?.max ?? -1) + 1, createdAt: now, updatedAt: now }).run(); return this.list(userId).find((item) => item.id === categoryId); }
  updateTopic(userId: string, id: string, input: TitleInput) { const topic = this.ensureTopic(userId, id); this.db.update(technicalDebtPlaybookTopicsTable).set({ title: input.title, updatedAt: this.now() }).where(eq(technicalDebtPlaybookTopicsTable.id, id)).run(); return this.list(userId).find((item) => item.id === topic.categoryId); }
  deleteTopic(userId: string, id: string) { this.ensureTopic(userId, id); this.db.delete(technicalDebtPlaybookTopicsTable).where(eq(technicalDebtPlaybookTopicsTable.id, id)).run(); return { success: true }; }
  createDocument(userId: string, topicId: string, input: DocumentInput) { const topic = this.ensureTopic(userId, topicId); const id = `technicaldebt-doc-${randomUUID().slice(0, 12)}`; const now = this.now(); const max = this.db.select({ max: sql<number>`coalesce(max(${technicalDebtPlaybookDocumentsTable.orderIdx}), -1)` }).from(technicalDebtPlaybookDocumentsTable).where(eq(technicalDebtPlaybookDocumentsTable.topicId, topicId)).get(); this.db.insert(technicalDebtPlaybookDocumentsTable).values({ id, topicId, title: input.title, content: input.content, orderIdx: Number(max?.max ?? -1) + 1, createdAt: now, updatedAt: now }).run(); return this.list(userId).find((item) => item.id === topic.categoryId); }
  updateDocument(userId: string, id: string, input: DocumentPatchInput) { const document = this.ensureDocument(userId, id); this.db.update(technicalDebtPlaybookDocumentsTable).set({ ...(input.title !== undefined ? { title: input.title } : {}), ...(input.content !== undefined ? { content: input.content } : {}), updatedAt: this.now() }).where(eq(technicalDebtPlaybookDocumentsTable.id, id)).run(); return this.list(userId).find((item) => item.topics.some((topic) => topic.id === document.topicId)); }
  deleteDocument(userId: string, id: string) { this.ensureDocument(userId, id); this.db.delete(technicalDebtPlaybookDocumentsTable).where(eq(technicalDebtPlaybookDocumentsTable.id, id)).run(); return { success: true }; }
  reorderDocument(userId: string, id: string, direction: 'up' | 'down') { const document = this.ensureDocument(userId, id); const siblings = this.db.select().from(technicalDebtPlaybookDocumentsTable).where(eq(technicalDebtPlaybookDocumentsTable.topicId, document.topicId)).orderBy(asc(technicalDebtPlaybookDocumentsTable.orderIdx)).all(); const index = siblings.findIndex((item) => item.id === id); const adjacent = siblings[direction === 'up' ? index - 1 : index + 1]; if (!adjacent) return this.list(userId); this.db.update(technicalDebtPlaybookDocumentsTable).set({ orderIdx: adjacent.orderIdx, updatedAt: this.now() }).where(eq(technicalDebtPlaybookDocumentsTable.id, document.id)).run(); this.db.update(technicalDebtPlaybookDocumentsTable).set({ orderIdx: document.orderIdx, updatedAt: this.now() }).where(eq(technicalDebtPlaybookDocumentsTable.id, adjacent.id)).run(); return this.list(userId); }

  private ensureCategory(userId: string, id: string) { const row = this.db.select().from(technicalDebtPlaybookCategoriesTable).where(eq(technicalDebtPlaybookCategoriesTable.id, id)).get(); if (!row) throw new NotFoundException('기술부채 영역을 찾을 수 없습니다.'); if (row.userId !== userId) throw new ForbiddenException('접근 권한이 없습니다.'); return row; }
  private ensureTopic(userId: string, id: string) { const row = this.db.select().from(technicalDebtPlaybookTopicsTable).where(eq(technicalDebtPlaybookTopicsTable.id, id)).get(); if (!row) throw new NotFoundException('기술부채 주제를 찾을 수 없습니다.'); this.ensureCategory(userId, row.categoryId); return row; }
  private ensureDocument(userId: string, id: string) { const row = this.db.select().from(technicalDebtPlaybookDocumentsTable).where(eq(technicalDebtPlaybookDocumentsTable.id, id)).get(); if (!row) throw new NotFoundException('기술부채 문서를 찾을 수 없습니다.'); this.ensureTopic(userId, row.topicId); return row; }
}
